server:
  port: 8085
  # HTTP通信時：false
  # HTTPS通信時：true（デフォルト）
  servlet:
    session:
      cookie:
        secure: false
logging:
  file:
    name: /Users/taiseikato/Projects/ibooks/logs/general.log
  level:
    root: INFO
    org:
      seasar:
        doma: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibooks
    username: ibooks
    password: ibooks
    driverClassName: com.mysql.cj.jdbc.Driver
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
  config:
    import: "optional:file:/home/ibooks/config/local-general-config.yml"
env: develop
# 一般サイト設定
general-config:
  # 画像アップロード関連
  image:
    # ブック画像
    books:
      # 画像URL
      base-url: http://ibooks.local/img/book
      temp-base-url: http://ibooks.local/img/book/tmp